---
title: "outlierMBC"
author: "Ultán P. Doherty"
date: "2025-05-08"
output: github_document
---

```{r library, include=FALSE}
library(tidyverse)
library(outlierMBC)
```

## Gaussian Mixture Models

```{r ombc_gmm}
gross_gmm_k3n1000o10 <- find_gross(gmm_k3n1000o10[, 1:2], max_out = 20)

ombc_gmm_k3n1000o10 <- ombc_gmm(
  gmm_k3n1000o10[, 1:2],
  comp_num = 3, max_out = 20, gross_outs = gross_gmm_k3n1000o10$gross_bool
)

print(ombc_gmm_k3n1000o10)

plot(ombc_gmm_k3n1000o10)

gmm_k3n1000o10 |>
  mutate("ombc" = as.factor(ombc_gmm_k3n1000o10$labels), G = as.factor(G)) |>
  ggplot(aes(x = X1, y = X2, colour = ombc, shape = G)) +
  geom_point() +
  labs(colour = "outlierMBC", shape = "Simulation") +
  ggokabeito::scale_colour_okabe_ito(order = c(9, 1:3))
```

## Linear Cluster-Weighted Models

```{r ombc_lcwm}
gross_lcwm_k3n1000o10 <- find_gross(lcwm_k3n1000o10[, 1:2], max_out = 20)

ombc_lcwm_k3n1000o10 <- ombc_gmm(
  lcwm_k3n1000o10[, 1:2],
  comp_num = 3, max_out = 20, gross_outs = gross_lcwm_k3n1000o10$gross_bool
)

print(ombc_lcwm_k3n1000o10)

plot(ombc_lcwm_k3n1000o10)

lcwm_k3n1000o10 |>
  mutate("ombc" = as.factor(ombc_lcwm_k3n1000o10$labels), G = as.factor(G)) |>
  ggplot(aes(x = X1, y = Y, colour = ombc, shape = G)) +
  geom_point() +
  labs(colour = "outlierMBC", shape = "Simulation") +
  ggokabeito::scale_colour_okabe_ito(order = c(9, 1:3))
```
